---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 王凯.
--- DateTime: 2025/6/8 22:09
---
local voucherId = ARGV[1]
local userId = ARGV[2]
--  库存key
local stockKey = "seckill:stock:" .. voucherId
--  订单key
local orderKey = "seckill:order:" .. voucherId

if (tonumber(redis.call("get", stockKey)) <= 0) then
    --  库存不足
    return 1
end


if (redis.call("sismember", orderKey, userId) == 1) then
    --  用户已经购买过
    return 2
end
redis.call("incrby", stockKey, -1)
redis.call("sadd", orderKey, userId)
return 0
